version: '3.8'
services:
  postgres:
    build: ./db
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - '$DB_PORT'
    volumes:
      - ./db/data:/var/lib/postgresql/data
    restart: always
    command: -p $DB_PORT
  api:
    container_name: api-container
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=$API_NODE_ENV
      - PORT=$API_PORT
      - DB_HOST=postgres
      - DB_PORT=$DB_PORT
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
    ports:
      - '$API_PORT:$API_PORT'
    depends_on:
      - postgres
    volumes:
      - /app/node_modules
  client_build:
    container_name: client_build-container
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV
      - REACT_APP_API_HOST
    volumes:
      - ./client/build:/app/build
      - /app/node_modules
    depends_on:
      - client_server
      - api
  client_server:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./client/build:/usr/share/nginx/html
      - ./client/config/nginx:/etc/nginx/conf.d/
