export const FETCH_RANKING = 'FETCH_RANKING';
export const CREATE_USER = 'CREATE_USER';
export const CREATE_INVITE_LINK = 'CREATE_INVITE_LINK';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
